FROM node:20-slim AS builder
WORKDIR /app

COPY package*.json ./
RUN NODE_ENV=development npm install --legacy-peer-deps --no-audit --no-fund

COPY . .
RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
